name: Cross-Platform Alpha Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile index.py
        mkdir dist_upload
        mv dist/* dist_upload/

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 这里是修复的关键
      with:
        name: flask-${{ runner.os }}
        path: dist_upload/*

  release:
    name: Create Alpha Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4  # 同样修复
      with:
        path: artifacts

    - name: List files (debug)
      run: ls -R artifacts

    - name: Create Alpha Release
      uses: softprops/action-gh-release@v1
      with:
        name: Alpha Release ${{ github.run_number }}
        tag_name: alpha-${{ github.run_number }}
        files: artifacts/**/*
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GIHTUB_TOKEN }}
